---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    user: root
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
    user: root
    command: /usr/sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: root
    privilege_escalation:
      become: false
  playbooks:
    prepare: prepare.yml

verifier:
  name: ansible
  name: ansible
